version: '3.8'
name: go-provider-pattern
services:
    go-provider-pattern:
        container_name: go-provider-pattern
        build: .
        ports:
            - 3005:3000
        volumes:
            - ./:/app
        env_file: .env
        networks:
            - app-network
        depends_on:
            - mongo-db
            - postgres-db
    mongo-db:
        image: mongo:4.1.8-xenial
        container_name: mongo-db
        restart: unless-stopped
        env_file: .env
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
            - MONGO_INITDB_DATABASE=$MONGO_DB
        volumes:
            - dbdata:/data/db
            - ./seeds/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
        networks:
            - app-network

    postgres-db:
        image: postgres:alpine
        container_name: postgres-db
        restart: unless-stopped
        env_file: .env
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./seeds/postgre/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
    pgdata:
